services:
  - type: web
    name: finance-tracker-backend
    env: python
    rootDir: Backend
    plan: free
    buildCommand: pip install -r /work/requirements.txt
    startCommand: gunicorn finance_tracker.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ""
      - key: CORS_ALLOWED_ORIGINS
        value: ""
      - key: CSRF_TRUSTED_ORIGINS
        value: ""
      - key: DATABASE_URL
        sync: false

